### ISSUE TITLE
Say DOES support Windows

### ISSUE THREAD

**Issue by TotallyInformation** [programmerqeu/node-red-contrib-say#8]
It would be great if you could update this. It simply does a native shell call to PowerShell and it works fine for standard use.

I'm also raising an issue in the say library itself as there are some very easy enhancements that they can implement to support some additional features.

https://learn-powershell.net/2013/12/04/give-powershell-a-voice-using-the-speechsynthesizer-class/

**Comment by vergissberlin** [comment]
**Hi @TotallyInformation !**

Thank you for your improvements!
I just updated the dependencies.
Feel free to test it in action.

kind regards
vergissberlin

**Comment by TotallyInformation** [comment]
Thanks, good work.
